# As an ML expert classify the voice as either maile/female so that first level of filtration is quicker. Also, in addition you will get exposed to SVM algorithm along with scaling techniques.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
os.getcwd()

'C:\\Users\\je638474\\Downloads'

In [3]:
os.chdir(r'C:\Users\je638474\Documents\JJ\Folders\Udemy\Python EDUREKA')

In [4]:
data = pd.read_csv('voice-classification.csv')

In [5]:
data.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [6]:
#check for null values
#MVT not needed as there is no null values
data.isnull().sum()

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [7]:
#No outliers found

In [8]:
#'skew' and 'kurt' columns are not in the same range. Hence, has to do feature scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
data.iloc[:,6:8] = sc_x.fit_transform(data.iloc[:,6:8])

In [10]:
data.head()

meanfreq        sd    median       Q25       Q75       IQR      skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  2.293306   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  4.548056   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  6.513656   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374 -0.449858   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325 -0.480911   

       kurt    sp.ent       sfm  ...  centroid   meanfun    minfun    maxfun  \
0  1.762946  0.893369  0.491918  ...  0.059781  0.084279  0.015702  0.275862   
1  4.433008  0.892193  0.513724  ...  0.066009  0.107937  0.015826  0.250000   
2  7.326207  0.846389  0.478905  ...  0.077316  0.098706  0.015656  0.271186   
3 -0.240099  0.963322  0.727232  ...  0.151228  0.088965  0.017798  0.250000   
4 -0.238940  0.971955  0.783568  ...  0.135120  0.106398  0.016931  0.266667   

    meandom    mindom    maxdom   dfrange   modindx  label  
0  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [11]:
print ( "Shape of Data:" , data.shape)
print("Total number of labels: {}".format(data.shape[0]))
print("Number of male: {}".format(data[data.label == 'male'].shape[0]))
print("Number of female: {}".format(data[data.label == 'female'].shape[0]))

Shape of Data: (3168, 21)
Total number of labels: 3168
Number of male: 1584
Number of female: 1584


In [12]:
X=data.iloc[:, :-1]
print (data.shape)
print (X.shape)

(3168, 21)
(3168, 20)


In [13]:
#'label' coulum is categoriacal(male/female). Encoding to be executed here

In [14]:
from sklearn.preprocessing import LabelEncoder

In [60]:
# Get All rows, but only last column
y=data.iloc[:,-1]
# Encode label category
# male -> 1
# female -> 0

gender_encoder = LabelEncoder()
y = gender_encoder.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [61]:
type(y)

numpy.ndarray

In [16]:
# Scale the data to be between -1 and 1
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [17]:
data.tail()

meanfreq        sd    median       Q25       Q75       IQR      skew  \
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859 -0.325020   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193 -0.577009   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936 -0.298044   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435 -0.365367   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756 -0.338487   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
3163 -0.221916  0.962934  0.763182  ...  0.131884  0.182790  0.083770   
3164 -0.252503  0.960716  0.709570  ...  0.116221  0.188980  0.034409   
3165 -0.222108  0.946854  0.654196  ...  0.142056  0.209918  0.039506   
3166 -0.231123  0.950436  0.675470  ...  0.143659  0.172375  0.034483   
3167 -0.228300  0.938829  0.601529  ...  0.165509  0.185607  0.062257   

        maxfun   meandom    mindom    maxdom   dfrange   modindx   label  
3163  0.262295  0.832899  0.007812  4.210938  4.203125  0.161929  female  
3164  0.275862  0.909856  0.039062  3.679688  3.640625  0.277897  female  
3165  0.275862  0.494271  0.007812  2.937500  2.929688  0.194759  female  
3166  0.250000  0.791360  0.007812  3.593750  3.585938  0.311002  female  
3167  0.271186  0.227022  0.007812  0.554688  0.546875  0.350000  female  

[5 rows x 21 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

# Train a Model
Now its time to train a Support Vector Machine Classifier.

Call the SVC() model from sklearn and fit the model to the training data.

In [19]:
#SVM - Linear
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix
classifier_svc_lin = SVC(kernel='linear')
classifier_svc_lin.fit(X_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
y_pred_cl_svc_lin = classifier_svc_lin.predict(X_test)

In [24]:
y_pred_cl_svc_lin

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,

In [25]:
y_test

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,

In [26]:
#SVM - Sigmoid
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix
classifier_svc_sig = SVC(kernel='sigmoid')
classifier_svc_sig.fit(X_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [27]:
y_pred_cl_svc_sig = classifier_svc_sig.predict(X_test)

In [29]:
#SVM - poly
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix
classifier_svc_poly = SVC(kernel='poly')
classifier_svc_poly.fit(X_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [30]:
y_pred_cl_svc_poly = classifier_svc_sig.predict(X_test)

In [31]:
#SVM - rbf
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix
classifier_svc_rbf = SVC(kernel='rbf')
classifier_svc_rbf.fit(X_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [32]:
y_pred_cl_svc_rbf = classifier_svc_rbf.predict(X_test)

# Model Evaluation
Now get predictions from the model and print accuracy and create a confusion matrix and a classification report.
** Q1 What is the accuracy when default SVC model is used? **

In [44]:
#SVC Linear
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_pred_cl_svc_lin))
print(confusion_matrix(y_test,y_pred_cl_svc_lin))
print(classification_report(y_test,y_pred_cl_svc_lin))

Accuracy Score:
0.9716088328075709
[[456  15]
 [ 12 468]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       471
           1       0.97      0.97      0.97       480

    accuracy                           0.97       951
   macro avg       0.97      0.97      0.97       951
weighted avg       0.97      0.97      0.97       951



In [45]:
#SVC Sigmoid
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_pred_cl_svc_sig))
print(confusion_matrix(y_test,y_pred_cl_svc_sig))
print(classification_report(y_test,y_pred_cl_svc_sig))

Accuracy Score:
0.8212407991587802
[[393  78]
 [ 92 388]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       471
           1       0.83      0.81      0.82       480

    accuracy                           0.82       951
   macro avg       0.82      0.82      0.82       951
weighted avg       0.82      0.82      0.82       951



In [46]:
#SVC Poly
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_pred_cl_svc_poly))
print(confusion_matrix(y_test,y_pred_cl_svc_poly))
print(classification_report(y_test,y_pred_cl_svc_poly))

Accuracy Score:
0.8212407991587802
[[393  78]
 [ 92 388]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       471
           1       0.83      0.81      0.82       480

    accuracy                           0.82       951
   macro avg       0.82      0.82      0.82       951
weighted avg       0.82      0.82      0.82       951



In [47]:
#SVC rbf
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_pred_cl_svc_rbf))
print(confusion_matrix(y_test,y_pred_cl_svc_rbf))
print(classification_report(y_test,y_pred_cl_svc_rbf))

Accuracy Score:
0.9737118822292324
[[458  13]
 [ 12 468]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       471
           1       0.97      0.97      0.97       480

    accuracy                           0.97       951
   macro avg       0.97      0.97      0.97       951
weighted avg       0.97      0.97      0.97       951



In [39]:
#The accuracy for rbf is the best in comparison


Your model was pretty good.Let's see if we can tune the parameters to try to get even better (unlikely, and you probably would be satisfied with these results in real like because the data set is quite small, but the idea is you should practice using GridSearch.

# Gridsearch
** Import GridsearchCV from SciKit Learn.**
** Q2 . Does gridsearch improves the score? **

In [48]:
from sklearn.model_selection import GridSearchCV

In [49]:
#I want to run K nearest neighbour and find out the correct count of neighbours

In [50]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5)
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [51]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_neighbors':[5,11,21,31]}]
grid_search=GridSearchCV(estimator = classifier_knn, param_grid = parameters, scoring = 'accuracy', cv = 10)
grid_search=grid_search.fit(X_train, y_train)
best_accuracy=grid_search.best_score_
best_parameter=grid_search.best_params_

In [52]:
best_parameter

{'n_neighbors': 5}

In [53]:
best_accuracy

0.9697668256491786

In [54]:
#Now I want to know which Kernel (sig, linear, poly, rbf) is the best?
#Using rbf as per previous accuracy score.

In [56]:
from sklearn.model_selection import GridSearchCV
parameters = [{'kernel':['linear','rbf','sigmoid','poly']}]
grid_search=GridSearchCV(estimator = classifier_svc_rbf, param_grid = parameters, scoring = 'accuracy', cv = 10)
grid_search=grid_search.fit(X_train, y_train)
best_accuracy=grid_search.best_score_
best_parameter=grid_search.best_params_

In [57]:
best_parameter

{'kernel': 'rbf'}

In [58]:
best_accuracy

0.9810586604704252