# Obj: Fit a model using binary classification using logistic regression.•Identify correlated variables and form a less complex model

# Q) We will use acoustic features to distinguish a male voice from female. Load the dataset from “voice.csv”,identify the target variable and do a one-hot encoding for the same. Split the dataset in train-test with 20% of the data kept aside for testing. Fit a logistic regression model and measure the accuracy on the test set..Compute the correlation matrix that describes the dependence between all predictors and identify the predictors that are highly correlated.  Plot the correlation matrix using seaborn heatmapased on correlation remove those predictors that are correlated and fit a logistic regression model again and compare the accuracy with that of previous mode

In [3]:
import os
os.chdir(r'C:\Users\je638474\Documents\JJ\Folders\Udemy\Python EDUREKA')

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
data = pd.read_csv('voice.csv')

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencod_x = LabelEncoder()
data.iloc[:,-1] = labelencod_x.fit_transform(data.iloc[:,-1])

In [9]:
x=data.iloc[:,0:27].values

In [12]:
y=data.iloc[:,-1].values

In [13]:
x

array([[0.05978098, 0.06424127, 0.03202691, ..., 0.        , 0.        ,
        1.        ],
       [0.06600874, 0.06731003, 0.04022873, ..., 0.046875  , 0.05263158,
        1.        ],
       [0.0773155 , 0.08382942, 0.03671846, ..., 0.0078125 , 0.04651163,
        1.        ],
       ...,
       [0.14205626, 0.09579843, 0.18373124, ..., 2.9296875 , 0.19475862,
        0.        ],
       [0.14365874, 0.09062826, 0.18497617, ..., 3.5859375 , 0.31100218,
        0.        ],
       [0.16550895, 0.09288354, 0.18304392, ..., 0.546875  , 0.35      ,
        0.        ]])

In [14]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split (x,y, test_size = 0.2)

In [21]:
from sklearn.linear_model import LogisticRegression
Classification_Logistic = LogisticRegression()
Classification_Logistic.fit(x_train, y_train)

C:\Users\je638474\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
y_pred_cl_log = Classification_Logistic.predict(x_test)

In [24]:
y_pred_cl_log

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred_cl_log)

array([[337,   0],
       [  0, 297]], dtype=int64)

In [26]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred_cl_log)

1.0