# Obj: Learn to handle missing values, fit a decision tree and compare its accuracy with random forest classifier

# Questions:
    Let’s attempt to predict the survival of a horse based on various observed medical conditions. Load the data from ‘horses.csv’ and observe whether it contains missing values
    This dataset contains many categorical features, replace them with label encoding.
    Replace the missing values by the most frequent value in each column.
    Fit a decision tree classifier and observe the accuracy.
    Fit a random forest classifier and observe the accuracy.

In [2]:
import os
os.getcwd()

'C:\\Users\\je638474\\Downloads'

In [5]:
os.chdir(r'C:\Users\je638474\Documents\JJ\Folders\Udemy\Python EDUREKA')

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
data = pd.read_csv('horse.csv')

In [12]:
len(data)

299

In [13]:
data.isnull().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities       56
peripheral_pulse          69
mucous_membrane           47
capillary_refill_time     32
pain                      55
peristalsis               44
abdominal_distention      56
nasogastric_tube         104
nasogastric_reflux       106
nasogastric_reflux_ph    246
rectal_exam_feces        102
abdomen                  118
packed_cell_volume        29
total_protein             33
abdomo_appearance        165
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencod_x = LabelEncoder()
data.iloc[:,0] = labelencod_x.fit_transform(data.iloc[:,0])

In [23]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencod_x = LabelEncoder()
data.iloc[:,23] = labelencod_x.fit_transform(data.iloc[:,23])

In [24]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencod_x = LabelEncoder()
data.iloc[:,27] = labelencod_x.fit_transform(data.iloc[:,27])

In [64]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencod_x = LabelEncoder()
data.iloc[:,1] = labelencod_x.fit_transform(data.iloc[:,1])

In [29]:
pd.concat([pd.get_dummies(data['surgery']), data] , axis = 1)

0  1  surgery  age  hospital_number  rectal_temp  pulse  \
0    1  0        0    0           530101         38.5   66.0   
1    0  1        1    0           534817         39.2   88.0   
2    1  0        0    0           530334         38.3   40.0   
3    0  1        1    1          5290409         39.1  164.0   
4    1  0        0    0           530255         37.3  104.0   
..  .. ..      ...  ...              ...          ...    ...   
294  0  1        1    0           533886          NaN  120.0   
295  1  0        0    0           527702         37.2   72.0   
296  0  1        1    0           529386         37.5   72.0   
297  0  1        1    0           530612         36.5  100.0   
298  0  1        1    0           534618         37.2   40.0   

     respiratory_rate temp_of_extremities peripheral_pulse  ...  \
0                28.0                cool          reduced  ...   
1                20.0                 NaN              NaN  ...   
2                24.0              normal           normal  ...   
3                84.0                cold           normal  ...   
4                35.0                 NaN              NaN  ...   
..                ...                 ...              ...  ...   
294              70.0                cold              NaN  ...   
295              24.0                cool        increased  ...   
296              30.0                cold          reduced  ...   
297              24.0                cool          reduced  ...   
298              20.0                 NaN              NaN  ...   

    packed_cell_volume total_protein abdomo_appearance abdomo_protein  \
0                 45.0           8.4               NaN            NaN   
1                 50.0          85.0            cloudy            2.0   
2                 33.0           6.7               NaN            NaN   
3                 48.0           7.2     serosanguious            5.3   
4                 74.0           7.4               NaN            NaN   
..                 ...           ...               ...            ...   
294               55.0          65.0               NaN            NaN   
295               44.0           NaN     serosanguious            3.3   
296               60.0           6.8               NaN            NaN   
297               50.0           6.0     serosanguious            3.4   
298               36.0          62.0             clear            1.0   

        outcome surgical_lesion lesion_1  lesion_2 lesion_3 cp_data  
0          died               0    11300         0        0       0  
1    euthanized               0     2208         0        0       0  
2         lived               0        0         0        0       1  
3          died               1     2208         0        0       1  
4          died               0     4300         0        0       0  
..          ...             ...      ...       ...      ...     ...  
294  euthanized               0     3205         0        0       0  
295  euthanized               1     2208         0        0       1  
296        died               1     3205         0        0       0  
297       lived               1     2208         0        0       1  
298  euthanized               0     6112         0        0       0  

[299 rows x 30 columns]

In [49]:
x=data.iloc[:].values

In [50]:
x

array([[0, 0, 530101, ..., 0, 0, 0],
       [1, 0, 534817, ..., 0, 0, 0],
       [0, 0, 530334, ..., 0, 0, 1],
       ...,
       [1, 0, 529386, ..., 0, 0, 0],
       [1, 0, 530612, ..., 0, 0, 1],
       [1, 0, 534618, ..., 0, 0, 0]], dtype=object)

In [51]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp = imp.fit(x[:])
x[:] = imp.transform(x[:])
x

array([[0, 0, 530101, ..., 0, 0, 0],
       [1, 0, 534817, ..., 0, 0, 0],
       [0, 0, 530334, ..., 0, 0, 1],
       ...,
       [1, 0, 529386, ..., 0, 0, 0],
       [1, 0, 530612, ..., 0, 0, 1],
       [1, 0, 534618, ..., 0, 0, 0]], dtype=object)

In [52]:
x = data.iloc[:, 1:28].values

In [53]:
x

array([[0, 530101, 38.5, ..., 0, 0, 0],
       [0, 534817, 39.2, ..., 0, 0, 0],
       [0, 530334, 38.3, ..., 0, 0, 1],
       ...,
       [0, 529386, 37.5, ..., 0, 0, 0],
       [0, 530612, 36.5, ..., 0, 0, 1],
       [0, 534618, 37.2, ..., 0, 0, 0]], dtype=object)

In [54]:
y = data.iloc[:,0].values

In [55]:
y

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1], dtyp

In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3,random_state = 10)

In [61]:
x_train.astype(str)

array([['1', '534092', '39.7', ..., '0', '0', '0'],
       ['0', '530401', '37.9', ..., '0', '0', '1'],
       ['0', '535054', '38.6', ..., '0', '0', '0'],
       ...,
       ['0', '530233', '37.6', ..., '0', '0', '0'],
       ['0', '528461', '38.0', ..., '0', '0', '0'],
       ['0', '529865', '38.6', ..., '0', '0', '1']], dtype='<U13')

In [62]:
x_test.astype(str)

array([['0', '533692', '38.1', ..., '0', '0', '0'],
       ['0', '529667', '39.0', ..., '0', '0', '1'],
       ['0', '534938', '38.3', ..., '0', '0', '0'],
       ...,
       ['0', '533697', '38.0', ..., '0', '0', '0'],
       ['0', '528298', 'nan', ..., '0', '0', '1'],
       ['0', '535314', '38.7', ..., '0', '0', '0']], dtype='<U13')

In [67]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train, y_train)

ValueError: could not convert string to float: 'cool'

In [68]:
y_pred_dt = classifier_dt.predict(x_test)

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [69]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(criterion='entropy')
classifier_rf.fit(x_train, y_train)

ValueError: could not convert string to float: 'cool'

In [70]:
y_pred_rf = classifier_rf.predict(x_test)

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [71]:
#how to check which classification algortihm gives highest accuracy?
#sklearn metrics -confusin matrix, accuracy score

In [72]:
#Decision Tree
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred_dt)

NameError: name 'y_pred_dt' is not defined

In [73]:
#Random Forest
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred_rf)

NameError: name 'y_pred_rf' is not defined